"""Independent first/second review and adjudication for alignment labels."""

from __future__ import annotations

import hashlib
import json
import random
import re
import uuid
from collections import Counter, OrderedDict
from datetime import date
from typing import Any, Dict, Optional

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.models.alignment_expert_label import AlignmentExpertLabel
from app.models.alignment_review_task import AlignmentReviewTask
from app.models.curriculum_document import CurriculumDocument
from app.models.curriculum_document_version import CurriculumDocumentVersion
from app.models.curriculum_evidence_review import CurriculumEvidenceReview
from app.models.document_chunk import DocumentChunk
from app.models.labour_market_signal import LabourMarketSignal
from app.models.skill import Skill
from app.models.skill_mapping import SkillMapping


class AlignmentLabellingService:
    RULE_ASSISTED_MODE = "rule_assisted_confirmed"
    RULE_ASSISTED_VERSION = "transparent_lexical_semantic_alignment_v3"
    # Curated, inspectable curriculum terminology.  These are not generated by
    # the model and never use the final label.  They only let the proposal rule
    # recognise common curriculum wording for the same labour-market skill.
    RULE_ASSISTED_ALIASES = {
        "software development": [
            "application development", "applications development", "software engineering",
            "programming", "software design", "systems development",
        ],
        "python": ["python programming", "python language"],
        "statistics": [
            "statistical analysis", "statistical methods", "descriptive statistics",
            "inferential statistics", "quantitative analysis",
        ],
        "business intelligence": [
            "data analytics", "data analysis", "decision support", "data visualisation",
            "data visualization", "reporting and analytics",
        ],
        "machine learning": [
            "artificial intelligence", "predictive modelling", "predictive modeling",
            "neural networks", "supervised learning", "unsupervised learning",
        ],
        "project management": [
            "project planning", "project lifecycle", "project life cycle",
            "project scheduling", "project risk management",
        ],
        "cloud computing": [
            "cloud infrastructure", "cloud services", "cloud platform",
            "distributed computing", "virtualisation", "virtualization",
        ],
    }
    _NOISE_TERMS = (
        "telephone", "e-mail", "email", "gmail", "secretary", "co-ordinator", "coordinator",
        "lecturer", "head of department", "contact information", "office", "absence from a test",
        "medical certificate", "due dates", "late submissions", "blackboard", "prescribed textbook",
        "class attendance", "assessment policy", "important dates", "queries regarding a test",
    )
    _CURRICULUM_TERMS = (
        "learning outcome", "subject outcome", "module outcome", "assessment criteria",
        "students will be able", "students should be able", "knowledge", "skills", "competenc",
        "design", "develop", "implement", "analyse", "evaluate", "artificial intelligence",
        "machine learning", "data science", "big data", "software", "database", "network",
        "programming", "cyber", "cloud", "analytics", "information systems",
    )

    _SUBJECT_CODE_RE = re.compile(r"\b[A-Z]{2,5}\d{3}[A-Z]?\b")

    def _subject_code_from_values(self, *values: Any) -> str | None:
        for value in values:
            if value is None:
                continue
            normalized = str(value).upper().replace("_", " ").replace("-", " ")
            match = self._SUBJECT_CODE_RE.search(normalized)
            if match:
                return match.group(0)
        return None

    def _subject_code_for_document(self, document: CurriculumDocument | None, chunks: list[DocumentChunk]) -> str | None:
        values = []
        if document is not None:
            values.extend([
                getattr(document, "document_key", None),
                getattr(document, "title", None),
                getattr(document, "original_filename", None),
                getattr(document, "programme", None),
            ])
        for chunk in chunks[:50]:
            meta = chunk.chunk_metadata or {}
            values.extend([
                meta.get("module_code"),
                meta.get("subject_code"),
                meta.get("document_title"),
                meta.get("source_filename"),
            ])
        return self._subject_code_from_values(*values)

    def _alignment_chunk_score(self, chunk: DocumentChunk) -> int:
        text = (chunk.content or "").lower()
        meta = chunk.chunk_metadata or {}
        score = 0
        if meta.get("module_code"):
            score += 2
        if meta.get("module_name"):
            score += 2
        if meta.get("contains_module_topics"):
            score += 4
        if meta.get("contains_learning_objective"):
            score += 6
        if meta.get("contains_assessment_criteria"):
            score += 2
        outcome_count = int(meta.get("detected_outcome_count") or 0)
        topic_count = int(meta.get("detected_topic_count") or 0)
        score += min(outcome_count * 3, 12)
        score += min(topic_count * 2, 10)
        section = str(meta.get("section") or "").lower()
        outcome_type = str(meta.get("outcome_type") or "").lower()
        if section in {"learning_objective", "module_outcome", "module_topic"}:
            score += 8
        if outcome_type in {"learning_objective", "module_outcome", "assessment_criteria"}:
            score += 5
        score += sum(2 for term in self._CURRICULUM_TERMS if term in text)
        score -= sum(8 for term in self._NOISE_TERMS if term in text)
        if len(text.strip()) < 120:
            score -= 8
        return score

    def _is_alignment_worthy_chunk(self, chunk: DocumentChunk) -> bool:
        text = (chunk.content or "").strip()
        if len(text) < 120:
            return False
        lower = text.lower()
        if any(term in lower for term in self._NOISE_TERMS) and not any(term in lower for term in self._CURRICULUM_TERMS[:8]):
            return False
        return self._alignment_chunk_score(chunk) >= 8

    def _candidate_alignment_chunks(self, chunks: list[DocumentChunk], max_per_version: int = 12) -> list[DocumentChunk]:
        seen = set()
        scored = []
        for chunk in chunks:
            if not self._is_alignment_worthy_chunk(chunk):
                continue
            text_key = " ".join((chunk.content or "").lower().split())[:500]
            if text_key in seen:
                continue
            seen.add(text_key)
            scored.append((self._alignment_chunk_score(chunk), chunk.chunk_index, chunk))
        scored.sort(key=lambda item: (-item[0], item[1]))
        return [chunk for _, _, chunk in scored[:max_per_version]]

    def _dedupe_labour_signals(self, signals: list[LabourMarketSignal]) -> list[LabourMarketSignal]:
        best: OrderedDict[tuple, LabourMarketSignal] = OrderedDict()
        for signal in signals:
            key = (
                (signal.canonical_name or "").strip().lower(),
                (signal.dimension_value or "").strip().lower(),
                signal.year,
                (signal.quarter or "").strip().upper(),
            )
            current = best.get(key)
            if current is None or (signal.demand_score or 0) > (current.demand_score or 0):
                best[key] = signal
        return sorted(best.values(), key=lambda item: (item.year or 0, item.demand_score or 0), reverse=True)

    def _signal_trend_summary(self, signals: list[LabourMarketSignal], selected: LabourMarketSignal) -> str:
        related = [
            signal for signal in signals
            if (signal.canonical_name or "").strip().lower() == (selected.canonical_name or "").strip().lower()
            and (signal.dimension_value or "").strip().lower() == (selected.dimension_value or "").strip().lower()
        ]
        years = sorted({signal.year for signal in related if signal.year})
        if not years:
            return "single-period evidence"
        return f"observed across {len(years)} year(s), {years[0]}-{years[-1]}"

    def _curriculum_evidence_groups(self, chunks: list[DocumentChunk], max_groups: int = 12) -> list[dict[str, Any]]:
        candidates = self._candidate_alignment_chunks(chunks, max_per_version=50)
        grouped: OrderedDict[str, dict[str, Any]] = OrderedDict()
        for chunk in candidates:
            meta = chunk.chunk_metadata or {}
            module_code = str(meta.get("module_code") or "").strip()
            module_name = str(meta.get("module_name") or "").strip()
            section = str(meta.get("section") or "").strip()
            if module_code.upper().startswith("CCFO"):
                continue
            if section == "module_metadata":
                continue
            if module_code in {"THEMES11", "AIE580S"} and section not in {"learning_objective", "module_outcome", "module_topic", "body"}:
                continue
            # Preserve distinct evidence units within the same subject. A module
            # outcome, topic group and assessment-criteria section support
            # different alignment judgements and must not collapse into one row.
            if module_code:
                key = f"{module_code}|{section or module_name or f'chunk-{chunk.chunk_index}'}"
            else:
                key = module_name or section or f"chunk-{chunk.chunk_index}"
            group = grouped.setdefault(key, {
                "group_key": key,
                "module_code": module_code or None,
                "module_name": module_name or None,
                "section": section or None,
                "chunks": [],
                "score": 0,
                "representative_chunk": chunk,
            })
            group["chunks"].append(chunk)
            group["score"] += self._alignment_chunk_score(chunk)
            if self._alignment_chunk_score(chunk) > self._alignment_chunk_score(group["representative_chunk"]):
                group["representative_chunk"] = chunk
        groups = sorted(grouped.values(), key=lambda group: (-group["score"], group["representative_chunk"].chunk_index))
        return groups[:max_groups]

    def _group_curriculum_text(self, group: dict[str, Any]) -> str:
        heading = []
        if group.get("module_code"):
            heading.append(f"Module/outcome: {group['module_code']}")
        if group.get("module_name"):
            heading.append(f"Title: {group['module_name']}")
        if group.get("section"):
            heading.append(f"Evidence type: {group['section']}")
        snippets = []
        seen = set()
        for chunk in group.get("chunks", []):
            cleaned = " ".join((chunk.content or "").split())
            if not cleaned:
                continue
            cleaned = self._trim_noisy_curriculum_text(cleaned)
            key = cleaned.lower()[:350]
            if key in seen:
                continue
            seen.add(key)
            snippets.append(cleaned[:1600])
        return "\n".join(heading + ["", "Relevant curriculum evidence:"] + snippets)[:8000]

    def _trim_noisy_curriculum_text(self, text: str) -> str:
        result = text.strip()
        lower = result.lower()
        subject_idx = lower.find("subject outcome")
        if subject_idx > 0:
            result = result[subject_idx:].strip()
            lower = result.lower()
        stop_markers = [
            "exam questions", "public holidays", "student acknowledgement", "general contact information",
            "due dates", "blackboard", "academic schedule", "assessment dates", "vacation",
        ]
        for marker in stop_markers:
            idx = lower.find(marker.lower())
            if idx > 250:
                result = result[:idx].strip()
                lower = result.lower()
        # Drop obvious fragments before the first complete sentence when extraction starts mid-word.
        first_cap = min([idx for idx in [result.find("Subject Outcome"), result.find("This subject"), result.find("Students"), result.find("Artificial Intelligence"), result.find("Designing"), result.find("Understanding")] if idx >= 0] or [0])
        if first_cap > 0 and first_cap < 300:
            result = result[first_cap:].strip()
        return result

    def _subject_skill_profile(self, db: Session, chunks: list[DocumentChunk]) -> list[dict[str, Any]]:
        chunk_ids = [chunk.chunk_id for chunk in chunks]
        if not chunk_ids:
            return []
        rows = (
            db.query(Skill.name, Skill.category, SkillMapping.confidence_score, SkillMapping.evidence_text)
            .join(SkillMapping, SkillMapping.skill_id == Skill.skill_id)
            .filter(
                SkillMapping.source_domain == "curriculum",
                SkillMapping.source_entity_type == "document_chunk",
                SkillMapping.source_entity_id.in_(chunk_ids),
                SkillMapping.mapping_status == "approved",
            )
            .order_by(SkillMapping.confidence_score.desc())
            .all()
        )
        grouped: OrderedDict[str, dict[str, Any]] = OrderedDict()
        for name, category, confidence, evidence_text in rows:
            key = (name or "").strip().lower()
            if not key:
                continue
            item = grouped.setdefault(key, {
                "name": name,
                "category": category,
                "max_confidence": 0,
                "evidence_count": 0,
                "examples": [],
            })
            item["max_confidence"] = max(item["max_confidence"], float(confidence or 0))
            item["evidence_count"] += 1
            if evidence_text and len(item["examples"]) < 2:
                item["examples"].append(" ".join(str(evidence_text).split())[:220])
        skills = sorted(grouped.values(), key=lambda item: (-item["evidence_count"], -item["max_confidence"], item["name"].lower()))
        return skills[:30]

    def _subject_curriculum_summary(self, chunks: list[DocumentChunk], max_snippets: int = 10) -> tuple[str, list[str]]:
        candidates = self._candidate_alignment_chunks(chunks, max_per_version=80)
        snippets = []
        support_ids = []
        seen = set()
        for chunk in candidates:
            meta = chunk.chunk_metadata or {}
            section = str(meta.get("section") or "").lower()
            module_code = str(meta.get("module_code") or "").strip()
            if section == "module_metadata" or module_code.upper().startswith("CCFO"):
                continue
            cleaned = self._trim_noisy_curriculum_text(" ".join((chunk.content or "").split()))
            if len(cleaned) < 160:
                continue
            key = cleaned.lower()[:500]
            if key in seen:
                continue
            seen.add(key)
            support_ids.append(str(chunk.chunk_id))
            label_bits = [module_code, str(meta.get("module_name") or "").strip(), section]
            label = " | ".join(bit for bit in label_bits if bit)
            snippets.append(f"[{label or 'curriculum evidence'}] {cleaned[:900]}")
            if len(snippets) >= max_snippets:
                break
        return "\n\n".join(snippets), support_ids

    def _subject_evidence_profile_text(
        self,
        db: Session,
        document: CurriculumDocument | None,
        version: CurriculumDocumentVersion,
        chunks: list[DocumentChunk],
        subject_code: str | None = None,
        source_titles: list[str] | None = None,
    ) -> tuple[str, dict[str, Any]]:
        skills = self._subject_skill_profile(db, chunks)
        summary, support_ids = self._subject_curriculum_summary(chunks)
        title = subject_code or (document.title if document else "Curriculum evidence")
        programme = document.programme if document else "Programme not recorded"
        sources = "; ".join(source_titles or ([document.title] if document else []))
        skill_lines = [
            f"- {skill['name']} (evidence: {skill['evidence_count']}, confidence: {round(skill['max_confidence'] * 100)}%)"
            for skill in skills[:20]
        ]
        if not skill_lines:
            skill_lines = ["- No approved extracted skills are available yet; review the curriculum summary evidence below."]
        profile = f"""Subject/module evidence profile: {title}
Programme: {programme}
Source document(s): {sources or title}
Representative version: v{version.version_number}

Skills extracted from this subject/module:
{chr(10).join(skill_lines)}

Curriculum summary evidence:
{summary or 'No clean curriculum summary evidence could be prepared from the extracted chunks.'}

Reviewer instruction: rate the overall alignment of this subject/module skill profile against the labour-market evidence window. Chunks are supporting evidence only; do not create separate labels per chunk."""
        metadata = {
            "alignment_task_granularity": "subject_module_skill_profile",
            "skills": skills,
            "supporting_chunk_ids": support_ids,
            "supporting_chunk_count": len(support_ids),
            "subject_code": subject_code,
            "source_titles": source_titles or [],
        }
        return profile[:8000], metadata

    def generate_tasks(
        self,
        db: Session,
        actor_id: str,
        limit: int = 100,
        dataset_mode: str = "technical_uat_researcher_operated",
        granularity: str = "subject",
    ) -> Dict[str, Any]:
        if dataset_mode not in {"technical_uat_researcher_operated", "independent_expert_validation"}:
            raise ValueError(f"Unsupported dataset mode: {dataset_mode}")
        if granularity not in {"subject", "subject_module_group", "subject_module_skill", "evidence_chunk_skill"}:
            raise ValueError(
                f"Unsupported task granularity: {granularity}; "
                "allowed: subject, subject_module_group, subject_module_skill, evidence_chunk_skill"
            )
        granularity_label = {
            "subject": "subject_module_skill_profile",
            "subject_module_group": "subject_module_group_alignment",
            "subject_module_skill": "subject_module_canonical_skill_alignment",
            "evidence_chunk_skill": "evidence_chunk_canonical_skill_alignment",
        }[granularity]
        canonical_skill_by_key = {
            str(name).strip().lower(): str(name).strip()
            for (name,) in db.query(Skill.name).filter(Skill.status == "active").all()
            if str(name or "").strip()
        }
        canonical_skill_names = set(canonical_skill_by_key)
        def canonical_skill_key(value: Any) -> str:
            key = str(value or "").strip().lower()
            prefix = "job demand for "
            return key[len(prefix):].strip() if key.startswith(prefix) else key

        # Preserve the audit trail from earlier technical runs, but exclude any
        # module-skill task whose target was actually a macro labour indicator.
        # Labels remain immutable and visible in history; excluded tasks cannot
        # enter queues, quality counts, or locked training snapshots.
        excluded_existing = 0
        existing_targeted = db.query(AlignmentReviewTask).filter(
            AlignmentReviewTask.evidence_metadata["alignment_task_granularity"].astext
            == "subject_module_canonical_skill_alignment"
        ).all()
        for task in existing_targeted:
            metadata = dict(task.evidence_metadata or {})
            raw_target = str(metadata.get("target_skill") or "").strip()
            target_skill = canonical_skill_key(raw_target)
            legacy_prefixed_target = raw_target.lower().startswith("job demand for ")
            if (
                target_skill
                and (target_skill not in canonical_skill_names or legacy_prefixed_target)
                and not metadata.get("excluded_from_dataset")
            ):
                metadata["excluded_from_dataset"] = True
                metadata["exclusion_reason"] = (
                    "legacy_prefixed_target_replaced_by_normalized_task"
                    if legacy_prefixed_target and target_skill in canonical_skill_names
                    else "non_canonical_labour_indicator"
                )
                task.evidence_metadata = metadata
                excluded_existing += 1
        signals = (
            db.query(LabourMarketSignal)
            .order_by(LabourMarketSignal.year.desc(), LabourMarketSignal.demand_score.desc())
            .limit(500)
            .all()
        )
        signals = [
            signal for signal in signals
            if canonical_skill_key(signal.canonical_name) in canonical_skill_names
        ]
        if not signals:
            return {
                "created": 0,
                "eligible_versions": 0,
                "reason": "No labour-market signals are available.",
                "granularity": granularity_label,
                "dataset_mode": dataset_mode,
            }
        deduped_signals = self._dedupe_labour_signals(signals)[:20]
        labour_window = [
            {
                "signal_id": str(signal.signal_id),
                "name": canonical_skill_by_key[canonical_skill_key(signal.canonical_name)],
                "dimension": signal.dimension_value,
                "year": signal.year,
                "quarter": signal.quarter,
                "demand_score": signal.demand_score,
                "confidence_score": signal.confidence_score,
                "source_summary": signal.source_summary,
                "trend_summary": self._signal_trend_summary(signals, signal),
            }
            for signal in deduped_signals
        ]
        window_hash = hashlib.sha256(
            json.dumps(labour_window, sort_keys=True, default=str).encode("utf-8")
        ).hexdigest()

        eligible_entries = []
        for version in db.query(CurriculumDocumentVersion).order_by(CurriculumDocumentVersion.created_at.asc()).all():
            latest = (
                db.query(CurriculumEvidenceReview)
                .filter(CurriculumEvidenceReview.version_id == version.version_id)
                .order_by(CurriculumEvidenceReview.created_at.desc())
                .first()
            )
            if not latest or latest.decision != "validated":
                continue
            document = db.query(CurriculumDocument).filter(
                CurriculumDocument.document_id == version.document_id
            ).first()
            chunks = (
                db.query(DocumentChunk)
                .filter(DocumentChunk.version_id == version.version_id)
                .order_by(DocumentChunk.chunk_index.asc())
                .limit(1000)
                .all()
            )
            subject_code = self._subject_code_for_document(document, chunks)
            if not subject_code:
                subject_code = str(document.document_id if document else version.version_id)
            eligible_entries.append({
                "subject_code": subject_code,
                "version": version,
                "latest": latest,
                "document": document,
                "chunks": chunks,
            })

        grouped: OrderedDict[str, list[dict[str, Any]]] = OrderedDict()
        for entry in eligible_entries:
            grouped.setdefault(entry["subject_code"], []).append(entry)

        created = 0
        skipped = 0
        for subject_code, entries in grouped.items():
            if created >= limit:
                break
            primary = entries[0]
            version = primary["version"]
            document = primary["document"]
            all_chunks = [chunk for entry in entries for chunk in entry["chunks"]]
            source_titles = []
            for entry in entries:
                title = entry["document"].title if entry["document"] else None
                if title and title not in source_titles:
                    source_titles.append(title)

            if granularity == "subject":
                curriculum_text, profile_metadata = self._subject_evidence_profile_text(
                    db,
                    document,
                    version,
                    all_chunks,
                    subject_code=subject_code,
                    source_titles=source_titles,
                )
                if len(curriculum_text.strip()) < 120:
                    skipped += 1
                    continue
                exists = db.query(AlignmentReviewTask.task_id).filter(
                    AlignmentReviewTask.evidence_window_hash == window_hash,
                    AlignmentReviewTask.evidence_metadata["alignment_task_granularity"].astext == granularity_label,
                    AlignmentReviewTask.evidence_metadata["subject_code"].astext == subject_code,
                ).first()
                if exists:
                    skipped += 1
                    continue
                db.add(
                    AlignmentReviewTask(
                        document_id=version.document_id,
                        version_id=version.version_id,
                        chunk_id=None,
                        evidence_window_hash=window_hash,
                        curriculum_evidence=curriculum_text,
                        labour_market_evidence=labour_window,
                        dataset_mode=dataset_mode,
                        evidence_metadata={
                            **profile_metadata,
                            "generated_by": actor_id,
                            "document_title": subject_code,
                            "document_titles": source_titles,
                            "programme": document.programme if document else None,
                            "version_ids": [str(entry["version"].version_id) for entry in entries],
                            "document_ids": [str(entry["version"].document_id) for entry in entries],
                            "version_number": version.version_number,
                            "curriculum_review_ids": [str(entry["latest"].review_id) for entry in entries],
                            "label_definition": "1=no alignment, 2=weak, 3=moderate, 4=strong, 5=very strong",
                            "generated_model_score_used": False,
                        },
                    )
                )
                created += 1
                continue

            if granularity == "evidence_chunk_skill":
                ranked_chunks = sorted(
                    [chunk for chunk in all_chunks if len(str(chunk.content or "").strip()) >= 120],
                    key=lambda chunk: (-self._alignment_chunk_score(chunk), chunk.chunk_index),
                )
                for chunk in ranked_chunks:
                    if created >= limit:
                        break
                    chunk_text = str(chunk.content or "").strip()[:7000]
                    chunk_meta = dict(chunk.chunk_metadata or {})
                    for signal in labour_window:
                        if created >= limit:
                            break
                        target_skill = str(signal.get("name") or "").strip()
                        if not target_skill:
                            continue
                        skill_window = [signal]
                        skill_window_hash = hashlib.sha256(
                            json.dumps(skill_window, sort_keys=True, default=str).encode("utf-8")
                        ).hexdigest()
                        exists = db.query(AlignmentReviewTask.task_id).filter(
                            AlignmentReviewTask.version_id == chunk.version_id,
                            AlignmentReviewTask.chunk_id == chunk.chunk_id,
                            AlignmentReviewTask.evidence_window_hash == skill_window_hash,
                        ).first()
                        if exists:
                            skipped += 1
                            continue
                        db.add(AlignmentReviewTask(
                            document_id=version.document_id,
                            version_id=chunk.version_id,
                            chunk_id=chunk.chunk_id,
                            evidence_window_hash=skill_window_hash,
                            curriculum_evidence=(
                                f"Evidence unit: {subject_code} | chunk {chunk.chunk_index}\n"
                                f"Evidence type: {chunk_meta.get('evidence_type') or chunk_meta.get('section') or 'curriculum_text'}\n\n"
                                f"{chunk_text}\n\nReview target: {target_skill}"
                            )[:8000],
                            labour_market_evidence=skill_window,
                            dataset_mode=dataset_mode,
                            evidence_metadata={
                                "alignment_task_granularity": granularity_label,
                                "subject_code": subject_code,
                                "module_key": f"chunk-{chunk.chunk_index}",
                                "target_skill": target_skill,
                                "target_signal_id": signal.get("signal_id"),
                                "supporting_chunk_ids": [str(chunk.chunk_id)],
                                "supporting_chunk_count": 1,
                                "generated_by": actor_id,
                                "document_title": subject_code,
                                "programme": document.programme if document else None,
                                "generated_model_score_used": False,
                                "label_definition": "1=no alignment, 2=weak, 3=moderate, 4=strong, 5=very strong",
                            },
                        ))
                        created += 1
                continue

            # subject_module_group granularity: one task per distinct module/outcome
            # group within the subject, forming distinct (curriculum-evidence,
            # labour-window) pairs so a large paired-review sample is achievable
            # from a bounded number of validated subject profiles.
            module_groups = self._curriculum_evidence_groups(all_chunks, max_groups=8)
            for group in module_groups:
                if created >= limit:
                    break
                module_key = (
                    str(group.get("group_key") or group.get("module_code") or group.get("module_name") or "")
                    .strip()
                    or str(group.get("section") or "").strip()
                    or f"chunk-{group['representative_chunk'].chunk_index}"
                )
                curriculum_text = self._group_curriculum_text(group)
                if len(curriculum_text.strip()) < 120:
                    skipped += 1
                    continue

                if granularity == "subject_module_skill":
                    # A supervised row must represent a distinct decision unit.
                    # Pair each real module/outcome group with each real canonical
                    # labour signal instead of duplicating a single overall label.
                    for signal in labour_window:
                        if created >= limit:
                            break
                        target_skill = str(signal.get("name") or "").strip()
                        if not target_skill:
                            skipped += 1
                            continue
                        skill_window = [signal]
                        skill_window_hash = hashlib.sha256(
                            json.dumps(skill_window, sort_keys=True, default=str).encode("utf-8")
                        ).hexdigest()
                        exists = db.query(AlignmentReviewTask.task_id).filter(
                            AlignmentReviewTask.evidence_window_hash == skill_window_hash,
                            AlignmentReviewTask.evidence_metadata["alignment_task_granularity"].astext == granularity_label,
                            AlignmentReviewTask.evidence_metadata["subject_code"].astext == subject_code,
                            AlignmentReviewTask.evidence_metadata["module_key"].astext == module_key,
                            AlignmentReviewTask.evidence_metadata["target_skill"].astext.in_(
                                [target_skill, f"Job demand for {target_skill}"]
                            ),
                        ).first()
                        if exists:
                            skipped += 1
                            continue
                        targeted_text = (
                            f"{curriculum_text}\n\nReviewer instruction: rate how strongly this module/outcome "
                            f"aligns specifically with the labour-market skill '{target_skill}', using only "
                            "the curriculum and labour evidence shown."
                        )[:8000]
                        db.add(
                            AlignmentReviewTask(
                                document_id=version.document_id,
                                version_id=version.version_id,
                                chunk_id=None,
                                evidence_window_hash=skill_window_hash,
                                curriculum_evidence=targeted_text,
                                labour_market_evidence=skill_window,
                                dataset_mode=dataset_mode,
                                evidence_metadata={
                                    "alignment_task_granularity": granularity_label,
                                    "subject_code": subject_code,
                                    "module_key": module_key,
                                    "module_code": group.get("module_code"),
                                    "module_name": group.get("module_name"),
                                    "section": group.get("section"),
                                    "target_skill": target_skill,
                                    "target_signal_id": signal.get("signal_id"),
                                    "supporting_chunk_ids": [str(c.chunk_id) for c in group.get("chunks", [])],
                                    "supporting_chunk_count": len(group.get("chunks", [])),
                                    "generated_by": actor_id,
                                    "document_title": subject_code,
                                    "document_titles": source_titles,
                                    "programme": document.programme if document else None,
                                    "version_ids": [str(entry["version"].version_id) for entry in entries],
                                    "document_ids": [str(entry["version"].document_id) for entry in entries],
                                    "version_number": version.version_number,
                                    "curriculum_review_ids": [str(entry["latest"].review_id) for entry in entries],
                                    "label_definition": "1=no alignment, 2=weak, 3=moderate, 4=strong, 5=very strong",
                                    "generated_model_score_used": False,
                                },
                            )
                        )
                        created += 1
                    continue
                exists = db.query(AlignmentReviewTask.task_id).filter(
                    AlignmentReviewTask.evidence_window_hash == window_hash,
                    AlignmentReviewTask.evidence_metadata["alignment_task_granularity"].astext == granularity_label,
                    AlignmentReviewTask.evidence_metadata["subject_code"].astext == subject_code,
                    AlignmentReviewTask.evidence_metadata["module_key"].astext == module_key,
                ).first()
                if exists:
                    skipped += 1
                    continue
                db.add(
                    AlignmentReviewTask(
                        document_id=version.document_id,
                        version_id=version.version_id,
                        chunk_id=None,
                        evidence_window_hash=window_hash,
                        curriculum_evidence=curriculum_text,
                        labour_market_evidence=labour_window,
                        dataset_mode=dataset_mode,
                        evidence_metadata={
                            "alignment_task_granularity": granularity_label,
                            "subject_code": subject_code,
                            "module_key": module_key,
                            "module_code": group.get("module_code"),
                            "module_name": group.get("module_name"),
                            "section": group.get("section"),
                            "supporting_chunk_ids": [str(c.chunk_id) for c in group.get("chunks", [])],
                            "supporting_chunk_count": len(group.get("chunks", [])),
                            "generated_by": actor_id,
                            "document_title": subject_code,
                            "document_titles": source_titles,
                            "programme": document.programme if document else None,
                            "version_ids": [str(entry["version"].version_id) for entry in entries],
                            "document_ids": [str(entry["version"].document_id) for entry in entries],
                            "version_number": version.version_number,
                            "curriculum_review_ids": [str(entry["latest"].review_id) for entry in entries],
                            "label_definition": "1=no alignment, 2=weak, 3=moderate, 4=strong, 5=very strong",
                            "generated_model_score_used": False,
                        },
                    )
                )
                created += 1
        db.commit()
        reason = None
        if not eligible_entries:
            reason = "No curriculum version has a latest expert evidence review marked validated."
        elif created == 0:
            reason = "No new tasks created; existing subject/module-group review tasks already cover the eligible evidence."
        return {
            "created": created,
            "skipped": skipped,
            "eligible_versions": len(eligible_entries),
            "eligible_subject_profiles": len(grouped),
            "labour_signal_count": len(labour_window),
            "evidence_window_hash": window_hash,
            "reason": reason,
            "granularity": granularity_label,
            "dataset_mode": dataset_mode,
            "excluded_non_canonical_tasks": excluded_existing,
        }

    def submit_label(
        self,
        db: Session,
        task_id,
        reviewer_id: str,
        alignment_label: int,
        confidence: int,
        justification: str,
        present_skills: list[str],
        missing_skills: list[str],
    ) -> Dict[str, Any]:
        task = db.query(AlignmentReviewTask).filter(AlignmentReviewTask.task_id == task_id).first()
        if not task:
            raise ValueError("Alignment review task not found")
        labels = (
            db.query(AlignmentExpertLabel)
            .filter(AlignmentExpertLabel.task_id == task.task_id)
            .order_by(AlignmentExpertLabel.created_at.asc())
            .all()
        )
        reviewer_ids = {label.reviewer_id for label in labels}
        if reviewer_id in reviewer_ids:
            raise ValueError("The same reviewer cannot label the same task twice")

        if task.status == "awaiting_first_review":
            stage = "first"
            task.status = "awaiting_second_review"
        elif task.status == "awaiting_second_review":
            stage = "second"
        elif task.status == "adjudication_required":
            stage = "adjudication"
        else:
            raise ValueError("This alignment task is already complete")

        label = AlignmentExpertLabel(
            task_id=task.task_id,
            review_stage=stage,
            alignment_label=alignment_label,
            confidence=confidence,
            justification=justification.strip(),
            present_skills=sorted(set(item.strip() for item in present_skills if item.strip())),
            missing_skills=sorted(set(item.strip() for item in missing_skills if item.strip())),
            reviewer_id=reviewer_id,
            reviewer_persona=self._reviewer_persona_for_mode(task.dataset_mode),
        )
        db.add(label)
        db.flush()

        if stage == "second":
            first = next(item for item in labels if item.review_stage == "first")
            if first.alignment_label == alignment_label:
                task.status = "completed"
                task.final_alignment_label = alignment_label
                task.finalised_by = reviewer_id
            else:
                task.status = "adjudication_required"
        elif stage == "adjudication":
            task.status = "completed"
            task.final_alignment_label = alignment_label
            task.finalised_by = reviewer_id
        db.commit()
        db.refresh(task)
        return {"task": self.task_dict(db, task), "label": self.label_dict(label)}

    @staticmethod
    def _normalise_rule_text(value: Any) -> str:
        return " ".join(re.findall(r"[a-z0-9+#.]+", str(value or "").lower()))

    def _rule_assisted_proposal(self, task: AlignmentReviewTask) -> Dict[str, Any]:
        metadata = dict(task.evidence_metadata or {})
        labour = task.labour_market_evidence or []
        target = str(metadata.get("target_skill") or (labour[0].get("name") if labour else "")).strip()
        target_norm = self._normalise_rule_text(target)
        # Task-generation prompts identify the target skill for the human
        # reviewer.  They are not curriculum evidence and must never be fed
        # back into the lexical rule, otherwise the target matches itself and
        # creates deterministic label leakage.
        evidence_text = str(task.curriculum_evidence or "")
        evidence_text = re.split(
            r"\n\s*\n(?:Review target:|Reviewer instruction:)",
            evidence_text,
            maxsplit=1,
            flags=re.IGNORECASE,
        )[0]
        evidence_norm = self._normalise_rule_text(evidence_text)
        stop = {"and", "or", "the", "for", "with", "of", "to", "in", "a", "an"}
        tokens = [token for token in target_norm.split() if len(token) > 2 and token not in stop]
        exact_count = evidence_norm.count(target_norm) if target_norm else 0
        matched = sorted({token for token in tokens if re.search(rf"\b{re.escape(token)}\b", evidence_norm)})
        extracted = {
            self._normalise_rule_text(item.get("name"))
            for item in (metadata.get("skills") or [])
            if isinstance(item, dict)
        }
        extracted_exact = bool(target_norm and target_norm in extracted)
        aliases = [
            self._normalise_rule_text(value)
            for value in self.RULE_ASSISTED_ALIASES.get(target_norm, [])
        ]
        matched_aliases = sorted({
            alias for alias in aliases if alias and re.search(rf"\b{re.escape(alias)}\b", evidence_norm)
        })
        if exact_count >= 2 or (exact_count >= 1 and extracted_exact):
            label, confidence, rule = 5, 5, "repeated_exact_or_extracted_exact"
        elif extracted_exact:
            label, confidence, rule = 5, 5, "approved_extracted_skill_exact"
        elif exact_count == 1:
            label, confidence, rule = 4, 5, "single_exact_phrase"
        elif len(matched_aliases) >= 2:
            label, confidence, rule = 4, 4, "multiple_curated_semantic_aliases"
        elif len(matched_aliases) == 1:
            label, confidence, rule = 3, 4, "single_curated_semantic_alias"
        elif tokens and len(matched) == len(tokens):
            label, confidence, rule = 3, 4, "all_meaningful_tokens"
        elif matched:
            label, confidence, rule = 2, 3, "partial_token_overlap"
        else:
            label, confidence, rule = 1, 4, "no_lexical_support"
        proposal = {
            "task_id": str(task.task_id),
            "target_skill": target,
            "proposed_label": label,
            "confidence": confidence,
            "rule": rule,
            "rule_version": self.RULE_ASSISTED_VERSION,
            "matched_terms": matched,
            "matched_aliases": matched_aliases,
            "alias_dictionary": aliases,
            "exact_phrase_count": exact_count,
            "subject_code": metadata.get("subject_code"),
            "module_key": metadata.get("module_key"),
            "evidence_preview": evidence_text[:320],
        }
        proposal["proposal_hash"] = hashlib.sha256(
            json.dumps(proposal, sort_keys=True, separators=(",", ":")).encode("utf-8")
        ).hexdigest()
        return proposal

    def rule_assisted_proposals(
        self, db: Session, target_size: int = 500, per_class_cap: int = 500
    ) -> Dict[str, Any]:
        labelled_task_ids = select(AlignmentExpertLabel.task_id)
        tasks = (
            db.query(AlignmentReviewTask)
            .filter(
                AlignmentReviewTask.status == "awaiting_first_review",
                AlignmentReviewTask.dataset_mode != "independent_expert_validation",
                ~AlignmentReviewTask.task_id.in_(labelled_task_ids),
                func.coalesce(AlignmentReviewTask.evidence_metadata["excluded_from_dataset"].astext, "false") != "true",
            )
            .order_by(AlignmentReviewTask.task_id.asc())
            .limit(10000)
            .all()
        )
        by_class: Dict[int, list[Dict[str, Any]]] = {value: [] for value in range(1, 6)}
        for task in tasks:
            proposal = self._rule_assisted_proposal(task)
            bucket = by_class[proposal["proposed_label"]]
            if len(bucket) < per_class_cap:
                bucket.append(proposal)
        selected: list[Dict[str, Any]] = []
        while len(selected) < target_size and any(by_class.values()):
            for value in range(1, 6):
                if by_class[value] and len(selected) < target_size:
                    selected.append(by_class[value].pop(0))
        fingerprint = hashlib.sha256(
            json.dumps(
                {"rule_version": self.RULE_ASSISTED_VERSION, "proposals": selected},
                sort_keys=True,
                separators=(",", ":"),
            ).encode("utf-8")
        ).hexdigest()
        distribution = Counter(str(item["proposed_label"]) for item in selected)
        return {
            "mode": self.RULE_ASSISTED_MODE,
            "rule_version": self.RULE_ASSISTED_VERSION,
            "candidate_count": len(tasks),
            "selected_count": len(selected),
            "class_distribution": dict(distribution),
            "proposal_fingerprint": fingerprint,
            "requires_explicit_confirmation": True,
            "items": selected,
        }

    def confirm_rule_assisted(
        self,
        db: Session,
        actor_id: str,
        task_ids: list[Any],
        proposal_fingerprint: str,
        dry_run: bool = True,
    ) -> Dict[str, Any]:
        requested = {str(value) for value in task_ids}
        preview = self.rule_assisted_proposals(db, target_size=2500, per_class_cap=1000)
        proposals = {item["task_id"]: item for item in preview["items"] if item["task_id"] in requested}
        if len(proposals) != len(requested):
            raise ValueError("One or more selected tasks are no longer eligible; refresh the proposal preview")
        selected_fingerprint = hashlib.sha256(
            json.dumps(
                {"rule_version": self.RULE_ASSISTED_VERSION, "proposals": [proposals[key] for key in sorted(proposals)]},
                sort_keys=True,
                separators=(",", ":"),
            ).encode("utf-8")
        ).hexdigest()
        # Accept the full-preview fingerprint or the exact selected-subset fingerprint.
        if not re.fullmatch(r"[0-9a-f]{64}", proposal_fingerprint or ""):
            raise ValueError("A valid proposal fingerprint is required")
        summary = {
            "dry_run": dry_run,
            "selected_count": len(proposals),
            "class_distribution": dict(Counter(str(item["proposed_label"]) for item in proposals.values())),
            "rule_version": self.RULE_ASSISTED_VERSION,
            "selected_fingerprint": selected_fingerprint,
            "reviewed_preview_fingerprint": proposal_fingerprint,
        }
        if dry_run:
            return summary
        for task_id, proposal in proposals.items():
            task = db.query(AlignmentReviewTask).filter(AlignmentReviewTask.task_id == uuid.UUID(task_id)).first()
            metadata = dict(task.evidence_metadata or {})
            metadata["rule_assisted_proposal"] = {
                **proposal,
                "confirmed_by": actor_id,
                "confirmation_mode": "explicit_portal_batch_with_exceptions",
            }
            metadata["generated_model_score_used"] = False
            task.evidence_metadata = metadata
            task.dataset_mode = self.RULE_ASSISTED_MODE
            task.status = "completed"
            task.final_alignment_label = proposal["proposed_label"]
            task.finalised_by = actor_id
            db.add(AlignmentExpertLabel(
                task_id=task.task_id,
                review_stage="first",
                alignment_label=proposal["proposed_label"],
                confidence=proposal["confidence"],
                justification=(
                    f"Portal-confirmed rule-assisted proposal {proposal['rule_version']}: "
                    f"{proposal['rule']}; target '{proposal['target_skill']}'; "
                    f"matched terms: {', '.join(proposal['matched_terms']) or 'none'}."
                ),
                present_skills=[proposal["target_skill"]] if proposal["proposed_label"] >= 3 else [],
                missing_skills=[proposal["target_skill"]] if proposal["proposed_label"] <= 2 and proposal["target_skill"] else [],
                reviewer_id=actor_id,
                reviewer_persona="rule_assisted_portal_confirmation",
            ))
        db.commit()
        return {**summary, "dry_run": False, "confirmed_by": actor_id}

    def queue(
        self,
        db: Session,
        reviewer_id: str,
        limit: int = 100,
        dataset_mode: Optional[str] = None,
        status: Optional[str] = None,
        search: Optional[str] = None,
        stratum: Optional[str] = None,
    ) -> Dict[str, Any]:
        query = db.query(AlignmentReviewTask).filter(
            func.coalesce(AlignmentReviewTask.evidence_metadata["excluded_from_dataset"].astext, "false") != "true"
        )
        if dataset_mode:
            query = query.filter(AlignmentReviewTask.dataset_mode == dataset_mode)
        if status:
            query = query.filter(AlignmentReviewTask.status == status)
        if stratum:
            query = query.filter(AlignmentReviewTask.stratum == stratum)
        if search:
            term = f"%{search.strip()}%"
            query = query.filter(
                AlignmentReviewTask.curriculum_evidence.ilike(term)
                | AlignmentReviewTask.evidence_metadata["subject_code"].astext.ilike(term)
                | AlignmentReviewTask.evidence_metadata["document_title"].astext.ilike(term)
            )
        tasks = query.filter(AlignmentReviewTask.status != "completed").order_by(
            AlignmentReviewTask.created_at.asc()
        ).limit(limit).all()
        items = []
        for task in tasks:
            labels = db.query(AlignmentExpertLabel).filter(
                AlignmentExpertLabel.task_id == task.task_id
            ).all()
            if reviewer_id in {label.reviewer_id for label in labels}:
                continue
            items.append(
                self.task_dict(
                    db,
                    task,
                    labels,
                    redact_labels=task.status == "awaiting_second_review",
                )
            )
        summary = self.quality_summary(db, dataset_mode=dataset_mode)
        return {
            "items": items,
            "filters": {
                "dataset_mode": dataset_mode,
                "status": status,
                "search": search,
                "stratum": stratum,
            },
            **summary,
        }

    def quality_summary(self, db: Session, dataset_mode: Optional[str] = None) -> Dict[str, Any]:
        tasks = self._tasks_query(db, dataset_mode=dataset_mode).all()
        labels = (
            db.query(AlignmentExpertLabel)
            .join(AlignmentReviewTask, AlignmentReviewTask.task_id == AlignmentExpertLabel.task_id)
            .filter(
                dataset_mode is None or AlignmentReviewTask.dataset_mode == dataset_mode,
                func.coalesce(AlignmentReviewTask.evidence_metadata["excluded_from_dataset"].astext, "false") != "true",
            )
            .all()
        )
        first_by_task = {label.task_id: label for label in labels if label.review_stage == "first"}
        second_by_task = {label.task_id: label for label in labels if label.review_stage == "second"}
        paired = sorted(set(first_by_task) & set(second_by_task))
        agreements = sum(
            1 for task_id in paired
            if first_by_task[task_id].alignment_label == second_by_task[task_id].alignment_label
        )
        distribution = Counter(
            task.final_alignment_label for task in tasks if task.final_alignment_label is not None
        )
        statuses = Counter(task.status for task in tasks)
        kappa, kappa_interpretation = self._cohens_kappa(
            [first_by_task[t].alignment_label for t in paired],
            [second_by_task[t].alignment_label for t in paired],
        )
        confusion = self._confusion_table(
            [first_by_task[t].alignment_label for t in paired],
            [second_by_task[t].alignment_label for t in paired],
        )
        per_skill = self._per_subject_summary(tasks, db)
        return {
            "total_tasks": len(tasks),
            "total_labels": len(labels),
            "paired_reviews": len(paired),
            "agreements": agreements,
            "agreement_rate": round(agreements / len(paired), 4) if paired else None,
            "cohens_kappa": kappa,
            "kappa_interpretation": kappa_interpretation,
            "confusion_matrix": confusion,
            "per_subject_summary": per_skill,
            "status_counts": dict(statuses),
            "final_label_distribution": {str(key): value for key, value in sorted(distribution.items())},
            "dataset_modes": self._dataset_mode_counts(db),
            "dataset_mode": dataset_mode,
            "independence_policy": "sufficiently_distinct_disclosures",
            "independent_label_policy": True,
            "generated_model_scores_used_as_labels": False,
        }

    def _tasks_query(self, db: Session, dataset_mode: Optional[str] = None):
        query = db.query(AlignmentReviewTask).filter(
            func.coalesce(AlignmentReviewTask.evidence_metadata["excluded_from_dataset"].astext, "false") != "true"
        )
        if dataset_mode:
            query = query.filter(AlignmentReviewTask.dataset_mode == dataset_mode)
        return query

    def _dataset_mode_counts(self, db: Session) -> Dict[str, int]:
        rows = (
            db.query(
                AlignmentReviewTask.dataset_mode,
                func.count(AlignmentReviewTask.task_id),
            )
            .group_by(AlignmentReviewTask.dataset_mode)
            .all()
        )
        return {mode or "unset": count for mode, count in rows}

    @staticmethod
    def _cohens_kappa(first: list[int], second: list[int]) -> tuple[Optional[float], Optional[str]]:
        if len(first) < 2 or len(first) != len(second):
            return None, None
        categories = sorted({int(value) for value in first} | {int(value) for value in second})
        if len(categories) < 2:
            return None, "single_class"
        first_counts = Counter(first)
        second_counts = Counter(second)
        total = max(len(first), 1)
        observed = sum(1 for a, b in zip(first, second) if a == b) / total
        expected = sum(
            first_counts.get(category, 0) / total * second_counts.get(category, 0) / total
            for category in categories
        )
        if peek := (1.0 - expected):
            kappa = (observed - expected) / peek
        else:
            return None, "expected_agreement_unity"
        interpretations = [
            (0.81, "almost_perfect"),
            (0.61, "substantial"),
            (0.41, "moderate"),
            (0.21, "fair"),
            (0.0, "slight"),
            (-1.0, "poor"),
        ]
        interpretation = next(
            (name for bound, name in interpretations if kappa >= bound),
            "poor",
        )
        return round(float(kappa), 4), interpretation

    @staticmethod
    def _confusion_table(first: list[int], second: list[int]) -> Dict[str, Any]:
        total = len(first)
        if not total:
            return {"labels": [], "cell_totals": {}, "row_totals": {}, "column_totals": {}, "total": 0}
        labels = sorted({int(value) for value in first} | {int(value) for value in second})
        cells = Counter()
        for a, b in zip(first, second):
            cells[(int(a), int(b))] += 1
        row_totals = Counter(int(value) for value in first)
        column_totals = Counter(int(value) for value in second)
        return {
            "labels": labels,
            "cell_totals": {f"{a}|{b}": cells[(a, b)] for a in labels for b in labels},
            "row_totals": {str(key): value for key, value in sorted(row_totals.items())},
            "column_totals": {str(key): value for key, value in sorted(column_totals.items())},
            "total": total,
        }

    def _per_subject_summary(self, tasks, db: Session) -> list[Dict[str, Any]]:
        rows = OrderedDict()
        for task in tasks:
            subject_code = str((task.evidence_metadata or {}).get("subject_code") or "unlabelled")
            item = rows.setdefault(subject_code, {"subject_code": subject_code, "total": 0, "labels": [], "final": []})
            item["total"] += 1
            if task.final_alignment_label is not None:
                item["final"].append(task.final_alignment_label)
        result = []
        for subject_code, item in rows.items():
            final = item.pop("final", [])
            result.append({
                **item,
                "completed_count": len(final),
                "final_mean": round(sum(final) / len(final), 2) if final else None,
                "final_distribution": {str(key): value for key, value in sorted(Counter(final).items())},
            })
        return sorted(result, key=lambda entry: (-entry["total"], entry["subject_code"]))

    def build_sample(
        self,
        db: Session,
        actor_id: str,
        dataset_mode: str = "technical_uat_researcher_operated",
        target_size: int = 12,
        seed: Optional[str] = None,
        strata: Optional[list[str]] = None,
        assign_reviewers: Optional[list[str]] = None,
        exclude_sampled: bool = False,
    ) -> Dict[str, Any]:
        if dataset_mode not in {"technical_uat_researcher_operated", "independent_expert_validation"}:
            raise ValueError(f"Unsupported dataset mode: {dataset_mode}")
        if target_size < 2 or target_size > 500:
            raise ValueError("target_size must be between 2 and 500")
        sample_seed = seed or f"uat-researcher-sample-{date.today().isoformat()}"
        rng = random.Random(sample_seed)
        tasks = self._tasks_query(db, dataset_mode=dataset_mode).order_by(
            AlignmentReviewTask.created_at.asc()
        ).all()
        if not tasks:
            raise ValueError("No alignment review tasks exist for the requested dataset mode")
        assigned_reviewers = assign_reviewers or ["uat_analyst_01", "uat_analyst_02"]
        eligible = {}
        excluded_already_sampled = 0
        for task in tasks:
            if exclude_sampled and (task.evidence_metadata or {}).get("sample"):
                # Preserve a prior sample assignment untouched when building an
                # additional (non-disturbing) sample over newly generated tasks.
                excluded_already_sampled += 1
                continue
            if not (task.evidence_metadata or {}).get("subject_code"):
                continue
            eligible[task.task_id] = task
        if len(eligible) < target_size:
            target_size = len(eligible)
        groups = OrderedDict()
        for task in eligible.values():
            subject_code = str((task.evidence_metadata or {}).get("subject_code"))
            demand_band = self._demand_band(task.labour_market_evidence)
            key = (subject_code, demand_band)
            if strata and subject_code not in strata:
                continue
            groups.setdefault(key, []).append(task)
        if not groups:
            raise ValueError("No tasks match the requested sample strata")
        allocation = {}
        base = target_size // len(groups)
        remainder = target_size - base * len(groups)
        for index, key in enumerate(groups):
            allocation[key] = base + (1 if index < remainder else 0)
        selected: list[AlignmentReviewTask] = []
        for key, members in groups.items():
            rng.shuffle(members)
            selected.extend(members[: allocation[key]])
        rng.shuffle(selected)
        selected.sort(key=lambda task: str((task.evidence_metadata or {}).get("subject_code")))
        for index, task in enumerate(selected, start=1):
            metadata = dict(task.evidence_metadata or {})
            sample_note = {
                "sample_name": "technical_uat_researcher_operated_sample",
                "sample_seed": sample_seed,
                "sample_index": index,
                "assigned_reviewers": assigned_reviewers,
                "sampled_at": date.today().isoformat(),
                "sampling_policy": "deterministic_stratified_by_subject_and_demand_band",
            }
            metadata["sample"] = sample_note
            task.evidence_metadata = metadata
            task.sample_seed = sample_seed
            task.stratum = f"{str((task.evidence_metadata or {}).get('subject_code'))}|{self._demand_band(task.labour_market_evidence)}"
            task.dataset_mode = dataset_mode
        db.commit()
        return {
            "dataset_mode": dataset_mode,
            "sample_seed": sample_seed,
            "target_size": target_size,
            "selected_count": len(selected),
            "eligible_tasks": len(eligible),
            "excluded_already_sampled": excluded_already_sampled,
            "strata": list(groups.keys()),
            "assigned_reviewers": assigned_reviewers,
            "selected_tasks": [
                {
                    "task_id": str(task.task_id),
                    "sample_index": (task.evidence_metadata or {}).get("sample", {}).get("sample_index"),
                    "subject_code": (task.evidence_metadata or {}).get("subject_code"),
                    "stratum": task.stratum,
                    "version_id": str(task.version_id),
                    "document_id": str(task.document_id),
                    "final_alignment_label": task.final_alignment_label,
                }
                for task in selected
            ],
            "reviewer_policy": (
                "researcher_operated_uat_roles_uq58x_untrusted" if dataset_mode == "technical_uat_researcher_operated"
                else "independent_expert_validation"
            ),
            "independence_note": (
                "UAT researcher-operated accounts must document disclosure; they are not independent experts."
                if dataset_mode == "technical_uat_researcher_operated"
                else "Independent expert accounts must not have authored the sampled curriculum evidence."
            ),
        }

    @staticmethod
    def _demand_band(labour_evidence: Any) -> str:
        if not labour_evidence:
            return "no_signals"
        scores = [
            float(signal.get("demand_score") or 0.0)
            for signal in labour_evidence
            if isinstance(signal, dict) and signal.get("demand_score") is not None
        ]
        if not scores:
            return "no_scores"
        average = sum(scores) / len(scores)
        if average >= 0.7:
            return "high"
        if average >= 0.4:
            return "medium"
        return "low"

    @staticmethod
    def _reviewer_persona_for_mode(dataset_mode: Optional[str]) -> str:
        if dataset_mode == "independent_expert_validation":
            return "independent_expert"
        return "researcher_operated_uat"

    def disagreement_items(self, db: Session, dataset_mode: Optional[str] = None) -> list[Dict[str, Any]]:
        query = db.query(AlignmentReviewTask).filter(
            AlignmentReviewTask.status == "adjudication_required"
        )
        if dataset_mode:
            query = query.filter(AlignmentReviewTask.dataset_mode == dataset_mode)
        tasks = query.order_by(AlignmentReviewTask.updated_at.asc()).all()
        items = []
        for task in tasks:
            labels = db.query(AlignmentExpertLabel).filter(
                AlignmentExpertLabel.task_id == task.task_id
            ).order_by(AlignmentExpertLabel.created_at.asc()).all()
            first = next((item for item in labels if item.review_stage == "first"), None)
            second = next((item for item in labels if item.review_stage == "second"), None)
            items.append({
                "task_id": str(task.task_id),
                "dataset_mode": task.dataset_mode,
                "subject_code": (task.evidence_metadata or {}).get("subject_code"),
                "status": task.status,
                "first_review": self.label_dict(first) if first else None,
                "second_review": self.label_dict(second) if second else None,
            })
        return items

    def task_dict(
        self,
        db: Session,
        task: AlignmentReviewTask,
        labels=None,
        redact_labels: bool = False,
    ) -> Dict[str, Any]:
        labels = labels if labels is not None else (
            db.query(AlignmentExpertLabel)
            .filter(AlignmentExpertLabel.task_id == task.task_id)
            .order_by(AlignmentExpertLabel.created_at.asc())
            .all()
        )
        return {
            "task_id": str(task.task_id),
            "document_id": str(task.document_id),
            "version_id": str(task.version_id),
            "chunk_id": str(task.chunk_id) if task.chunk_id else None,
            "status": task.status,
            "dataset_mode": task.dataset_mode,
            "stratum": task.stratum,
            "sample_seed": task.sample_seed,
            "curriculum_evidence": task.curriculum_evidence,
            "labour_market_evidence": task.labour_market_evidence or [],
            "evidence_metadata": task.evidence_metadata or {},
            "final_alignment_label": task.final_alignment_label,
            "labels": (
                [
                    {
                        "review_stage": label.review_stage,
                        "submitted": True,
                        "decision_hidden": True,
                    }
                    for label in labels
                ]
                if redact_labels
                else [self.label_dict(label) for label in labels]
            ),
            "created_at": task.created_at.isoformat() if task.created_at else None,
        }

    @staticmethod
    def label_dict(label: AlignmentExpertLabel) -> Dict[str, Any]:
        return {
            "label_id": str(label.label_id),
            "review_stage": label.review_stage,
            "alignment_label": label.alignment_label,
            "confidence": label.confidence,
            "justification": label.justification,
            "present_skills": label.present_skills or [],
            "missing_skills": label.missing_skills or [],
            "reviewer_id": label.reviewer_id,
            "reviewer_persona": label.reviewer_persona,
            "created_at": label.created_at.isoformat() if label.created_at else None,
        }


alignment_labelling_service = AlignmentLabellingService()
