"""enterprise auth audit rbac enhancements

Revision ID: 91de4aeb6905
Revises: 7a68abe49b88
Create Date: 2026-05-29 19:38:40.425683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91de4aeb6905'
down_revision: Union[str, Sequence[str], None] = '7a68abe49b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_curriculum_active_code', table_name='curriculum_module')
    op.drop_index('ix_curriculum_faculty', table_name='curriculum_module')
    op.drop_index('ix_curriculum_faculty_nqf', table_name='curriculum_module')
    op.drop_index('ix_curriculum_module_code', table_name='curriculum_module')
    op.drop_index('ix_curriculum_nqf_level', table_name='curriculum_module')
    op.create_index(op.f('ix_curriculum_module_faculty'), 'curriculum_module', ['faculty'], unique=False)
    op.create_index(op.f('ix_curriculum_module_module_code'), 'curriculum_module', ['module_code'], unique=True)
    op.create_index(op.f('ix_curriculum_module_nqf_level'), 'curriculum_module', ['nqf_level'], unique=False)
    op.create_index(op.f('ix_curriculum_module_programme'), 'curriculum_module', ['programme'], unique=False)
    op.drop_table_comment(
        'curriculum_module',
        existing_comment='Curriculum modules for predictive alignment analysis',
        schema=None
    )
    op.alter_column('dsl01_auditevent', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_index('ix_audit_actor', table_name='dsl01_auditevent')
    op.drop_index('ix_audit_actor_time', table_name='dsl01_auditevent')
    op.drop_index('ix_audit_event_time', table_name='dsl01_auditevent')
    op.drop_index('ix_audit_result', table_name='dsl01_auditevent')
    op.drop_index('ix_audit_token', table_name='dsl01_auditevent')
    op.drop_index('ix_audit_type', table_name='dsl01_auditevent')
    op.create_index('idx_audit_severity', 'dsl01_auditevent', ['severity'], unique=False)
    op.create_index('idx_audit_token_time', 'dsl01_auditevent', ['token_id', 'event_time'], unique=False)
    op.create_index('idx_audit_type_time', 'dsl01_auditevent', ['event_type', 'event_time'], unique=False)
    op.create_index(op.f('ix_dsl01_auditevent_actor_id'), 'dsl01_auditevent', ['actor_id'], unique=False)
    op.create_index(op.f('ix_dsl01_auditevent_token_id'), 'dsl01_auditevent', ['token_id'], unique=False)
    op.create_foreign_key(op.f('fk_dsl01_auditevent_token_id_sec01_authtoken'), 'dsl01_auditevent', 'sec01_authtoken', ['token_id'], ['token_id'], ondelete='SET NULL')
    op.drop_index('ix_job_created_at', table_name='job_posting')
    op.drop_index('ix_job_posting_month', table_name='job_posting')
    op.drop_index('ix_job_posting_year', table_name='job_posting')
    op.drop_index('ix_job_processed', table_name='job_posting')
    op.drop_index('ix_job_region_month', table_name='job_posting')
    op.create_index(op.f('ix_job_posting_posted_date'), 'job_posting', ['posted_date'], unique=False)
    op.drop_table_comment(
        'job_posting',
        existing_comment='Labour market job postings for skills demand analysis',
        schema=None
    )
    op.alter_column('jus01_systemidentity', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_identity_email', table_name='jus01_systemidentity')
    op.drop_index('ix_identity_status', table_name='jus01_systemidentity')
    op.drop_index('ix_identity_type', table_name='jus01_systemidentity')
    op.execute('ALTER TABLE jus01_systemidentity DROP CONSTRAINT IF EXISTS jus01_systemidentity_email_key')
    op.create_index('idx_identity_active', 'jus01_systemidentity', ['is_active'], unique=False)
    op.create_index('idx_identity_email', 'jus01_systemidentity', ['email'], unique=False)
    op.create_index('idx_identity_status', 'jus01_systemidentity', ['status'], unique=False)
    op.create_index('idx_identity_type', 'jus01_systemidentity', ['identity_type'], unique=False)
    op.create_index(op.f('ix_jus01_systemidentity_email'), 'jus01_systemidentity', ['email'], unique=True)
    op.create_index(op.f('ix_jus01_systemidentity_identity_type'), 'jus01_systemidentity', ['identity_type'], unique=False)
    op.create_index(op.f('ix_jus01_systemidentity_is_active'), 'jus01_systemidentity', ['is_active'], unique=False)
    op.create_index(op.f('ix_jus01_systemidentity_status'), 'jus01_systemidentity', ['status'], unique=False)
    op.drop_index('ix_pred_aligned', table_name='predictive_output')
    op.drop_index('ix_pred_model_type', table_name='predictive_output')
    op.drop_index('ix_pred_module_code', table_name='predictive_output')
    op.drop_index('ix_pred_module_ts', table_name='predictive_output')
    op.drop_index('ix_pred_timestamp', table_name='predictive_output')
    op.create_index(op.f('ix_predictive_output_curriculum_module_code'), 'predictive_output', ['curriculum_module_code'], unique=False)
    op.create_index(op.f('ix_predictive_output_prediction_timestamp'), 'predictive_output', ['prediction_timestamp'], unique=False)
    op.drop_table_comment(
        'predictive_output',
        existing_comment='Predictive model outputs with explainability and audit metadata',
        schema=None
    )
    op.alter_column('sec01_authtoken', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_index('ix_authtoken_expiry', table_name='sec01_authtoken')
    op.drop_index('ix_authtoken_hash', table_name='sec01_authtoken')
    op.drop_index('ix_authtoken_revoked', table_name='sec01_authtoken')
    op.drop_index('ix_authtoken_subject', table_name='sec01_authtoken')
    op.drop_index('ix_authtoken_subject_revoked', table_name='sec01_authtoken')
    op.execute('ALTER TABLE sec01_authtoken DROP CONSTRAINT IF EXISTS uq_authtoken_token_hash')
    op.create_index('idx_authtoken_last_used', 'sec01_authtoken', ['last_used_at'], unique=False)
    op.create_index('idx_authtoken_revoked', 'sec01_authtoken', ['revoked'], unique=False)
    op.create_index('idx_authtoken_subject', 'sec01_authtoken', ['subject_id'], unique=False)
    op.create_index('idx_authtoken_subject_active', 'sec01_authtoken', ['subject_id', 'revoked', 'expires_at'], unique=False)
    op.create_index('idx_authtoken_subject_expiry', 'sec01_authtoken', ['subject_id', 'expires_at'], unique=False)
    op.create_unique_constraint(op.f('uq_sec01_authtoken_token_hash'), 'sec01_authtoken', ['token_hash'])
    op.add_column(
        'sec02_role',
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )

    op.add_column(
        'sec02_role',
        sa.Column(
            'is_system_role',
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.execute('ALTER TABLE sec02_role DROP CONSTRAINT IF EXISTS uq_sec02_role_role_name')
    op.create_index('idx_role_active', 'sec02_role', ['is_active'], unique=False)
    op.create_index('idx_role_active_name', 'sec02_role', ['is_active', 'role_name'], unique=False)
    op.create_index('idx_role_system', 'sec02_role', ['is_system_role'], unique=False)
    op.create_index(op.f('ix_sec02_role_role_name'), 'sec02_role', ['role_name'], unique=True)
    op.add_column('sec03_permission', sa.Column('resource', sa.String(length=100), nullable=True))
    op.add_column(
        'sec03_permission',
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )

    op.add_column(
        'sec03_permission',
        sa.Column(
            'is_system_permission',
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.execute(
        """
        UPDATE sec03_permission
        SET permission_name = permission_id
        WHERE permission_name IS NULL
        """
    )

    op.alter_column(
        'sec03_permission',
        'permission_name',
        existing_type=sa.VARCHAR(length=150),
        nullable=False
    )
    op.execute('ALTER TABLE sec03_permission DROP CONSTRAINT IF EXISTS uq_sec03_permission_permission_name')
    op.create_index('idx_permission_active', 'sec03_permission', ['is_active'], unique=False)
    op.create_index('idx_permission_active_name', 'sec03_permission', ['is_active', 'permission_name'], unique=False)
    op.create_index('idx_permission_resource', 'sec03_permission', ['resource'], unique=False)
    op.create_index('idx_permission_resource_active', 'sec03_permission', ['resource', 'is_active'], unique=False)
    op.create_index('idx_permission_system', 'sec03_permission', ['is_system_permission'], unique=False)
    op.create_index(op.f('ix_sec03_permission_permission_name'), 'sec03_permission', ['permission_name'], unique=True)
    op.create_index(op.f('ix_sec03_permission_resource'), 'sec03_permission', ['resource'], unique=False)
    op.add_column(
        'sec04_rolepermission',
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.create_index('idx_rolepermission_active', 'sec04_rolepermission', ['is_active'], unique=False)
    op.create_index('idx_rolepermission_permission', 'sec04_rolepermission', ['permission_id'], unique=False)
    op.create_index('idx_rolepermission_permission_active', 'sec04_rolepermission', ['permission_id', 'is_active'], unique=False)
    op.create_index('idx_rolepermission_role', 'sec04_rolepermission', ['role_id'], unique=False)
    op.create_index('idx_rolepermission_role_active', 'sec04_rolepermission', ['role_id', 'is_active'], unique=False)
    op.execute('ALTER TABLE sec04_rolepermission DROP CONSTRAINT IF EXISTS sec04_rolepermission_permission_id_fkey')
    op.execute('ALTER TABLE sec04_rolepermission DROP CONSTRAINT IF EXISTS sec04_rolepermission_role_id_fkey')
    op.execute('ALTER TABLE sec04_rolepermission DROP CONSTRAINT IF EXISTS fk_sec04_rolepermission_permission_id_sec03_permission')
    op.execute('ALTER TABLE sec04_rolepermission DROP CONSTRAINT IF EXISTS fk_sec04_rolepermission_role_id_sec02_role')
    op.create_foreign_key(op.f('fk_sec04_rolepermission_permission_id_sec03_permission'), 'sec04_rolepermission', 'sec03_permission', ['permission_id'], ['permission_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_sec04_rolepermission_role_id_sec02_role'), 'sec04_rolepermission', 'sec02_role', ['role_id'], ['role_id'], ondelete='CASCADE')
    op.add_column(
        'sec05_userrole',
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.create_index('idx_identityrole_active', 'sec05_userrole', ['is_active'], unique=False)
    op.create_index('idx_identityrole_identity', 'sec05_userrole', ['identity_id'], unique=False)
    op.create_index('idx_identityrole_identity_active', 'sec05_userrole', ['identity_id', 'is_active'], unique=False)
    op.create_index('idx_identityrole_role', 'sec05_userrole', ['role_id'], unique=False)
    op.create_index('idx_identityrole_role_active', 'sec05_userrole', ['role_id', 'is_active'], unique=False)
    op.execute('ALTER TABLE sec05_userrole DROP CONSTRAINT IF EXISTS sec05_userrole_identity_id_fkey')
    op.execute('ALTER TABLE sec05_userrole DROP CONSTRAINT IF EXISTS sec05_userrole_role_id_fkey')
    op.execute('ALTER TABLE sec05_userrole DROP CONSTRAINT IF EXISTS fk_sec05_userrole_identity_id_jus01_systemidentity')
    op.execute('ALTER TABLE sec05_userrole DROP CONSTRAINT IF EXISTS fk_sec05_userrole_role_id_sec02_role')
    op.create_foreign_key(op.f('fk_sec05_userrole_identity_id_jus01_systemidentity'), 'sec05_userrole', 'jus01_systemidentity', ['identity_id'], ['identity_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_sec05_userrole_role_id_sec02_role'), 'sec05_userrole', 'sec02_role', ['role_id'], ['role_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sec05_userrole_role_id_sec02_role'), 'sec05_userrole', type_='foreignkey')
    op.drop_constraint(op.f('fk_sec05_userrole_identity_id_jus01_systemidentity'), 'sec05_userrole', type_='foreignkey')
    op.create_foreign_key('sec05_userrole_role_id_fkey', 'sec05_userrole', 'sec02_role', ['role_id'], ['role_id'])
    op.create_foreign_key('sec05_userrole_identity_id_fkey', 'sec05_userrole', 'jus01_systemidentity', ['identity_id'], ['identity_id'])
    op.drop_index('idx_identityrole_role_active', table_name='sec05_userrole')
    op.drop_index('idx_identityrole_role', table_name='sec05_userrole')
    op.drop_index('idx_identityrole_identity_active', table_name='sec05_userrole')
    op.drop_index('idx_identityrole_identity', table_name='sec05_userrole')
    op.drop_index('idx_identityrole_active', table_name='sec05_userrole')
    op.drop_column('sec05_userrole', 'is_active')
    op.drop_constraint(op.f('fk_sec04_rolepermission_role_id_sec02_role'), 'sec04_rolepermission', type_='foreignkey')
    op.drop_constraint(op.f('fk_sec04_rolepermission_permission_id_sec03_permission'), 'sec04_rolepermission', type_='foreignkey')
    op.create_foreign_key('sec04_rolepermission_role_id_fkey', 'sec04_rolepermission', 'sec02_role', ['role_id'], ['role_id'])
    op.create_foreign_key('sec04_rolepermission_permission_id_fkey', 'sec04_rolepermission', 'sec03_permission', ['permission_id'], ['permission_id'])
    op.drop_index('idx_rolepermission_role_active', table_name='sec04_rolepermission')
    op.drop_index('idx_rolepermission_role', table_name='sec04_rolepermission')
    op.drop_index('idx_rolepermission_permission_active', table_name='sec04_rolepermission')
    op.drop_index('idx_rolepermission_permission', table_name='sec04_rolepermission')
    op.drop_index('idx_rolepermission_active', table_name='sec04_rolepermission')
    op.drop_column('sec04_rolepermission', 'is_active')
    op.drop_index(op.f('ix_sec03_permission_resource'), table_name='sec03_permission')
    op.drop_index(op.f('ix_sec03_permission_permission_name'), table_name='sec03_permission')
    op.drop_index('idx_permission_system', table_name='sec03_permission')
    op.drop_index('idx_permission_resource_active', table_name='sec03_permission')
    op.drop_index('idx_permission_resource', table_name='sec03_permission')
    op.drop_index('idx_permission_active_name', table_name='sec03_permission')
    op.drop_index('idx_permission_active', table_name='sec03_permission')
    op.create_unique_constraint('uq_sec03_permission_permission_name', 'sec03_permission', ['permission_name'])
    op.alter_column('sec03_permission', 'permission_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('sec03_permission', 'is_system_permission')
    op.drop_column('sec03_permission', 'is_active')
    op.drop_column('sec03_permission', 'resource')
    op.drop_index(op.f('ix_sec02_role_role_name'), table_name='sec02_role')
    op.drop_index('idx_role_system', table_name='sec02_role')
    op.drop_index('idx_role_active_name', table_name='sec02_role')
    op.drop_index('idx_role_active', table_name='sec02_role')
    op.create_unique_constraint('uq_sec02_role_role_name', 'sec02_role', ['role_name'])
    op.drop_column('sec02_role', 'is_system_role')
    op.drop_column('sec02_role', 'is_active')
    op.drop_constraint(op.f('uq_sec01_authtoken_token_hash'), 'sec01_authtoken', type_='unique')
    op.drop_index('idx_authtoken_subject_expiry', table_name='sec01_authtoken')
    op.drop_index('idx_authtoken_subject_active', table_name='sec01_authtoken')
    op.drop_index('idx_authtoken_subject', table_name='sec01_authtoken')
    op.drop_index('idx_authtoken_revoked', table_name='sec01_authtoken')
    op.drop_index('idx_authtoken_last_used', table_name='sec01_authtoken')
    op.create_unique_constraint('uq_authtoken_token_hash', 'sec01_authtoken', ['token_hash'])
    op.create_index('ix_authtoken_subject_revoked', 'sec01_authtoken', ['subject_id', 'revoked'], unique=False)
    op.create_index('ix_authtoken_subject', 'sec01_authtoken', ['subject_id'], unique=False)
    op.create_index('ix_authtoken_revoked', 'sec01_authtoken', ['revoked'], unique=False)
    op.create_index('ix_authtoken_hash', 'sec01_authtoken', ['token_hash'], unique=False)
    op.create_index('ix_authtoken_expiry', 'sec01_authtoken', ['expires_at'], unique=False)
    op.alter_column('sec01_authtoken', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_table_comment(
        'predictive_output',
        'Predictive model outputs with explainability and audit metadata',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_predictive_output_prediction_timestamp'), table_name='predictive_output')
    op.drop_index(op.f('ix_predictive_output_curriculum_module_code'), table_name='predictive_output')
    op.create_index('ix_pred_timestamp', 'predictive_output', ['prediction_timestamp'], unique=False)
    op.create_index('ix_pred_module_ts', 'predictive_output', ['curriculum_module_code', 'prediction_timestamp'], unique=False)
    op.create_index('ix_pred_module_code', 'predictive_output', ['curriculum_module_code'], unique=False)
    op.create_index('ix_pred_model_type', 'predictive_output', ['model_type'], unique=False)
    op.create_index('ix_pred_aligned', 'predictive_output', ['is_aligned'], unique=False)
    op.drop_index(op.f('ix_jus01_systemidentity_status'), table_name='jus01_systemidentity')
    op.drop_index(op.f('ix_jus01_systemidentity_is_active'), table_name='jus01_systemidentity')
    op.drop_index(op.f('ix_jus01_systemidentity_identity_type'), table_name='jus01_systemidentity')
    op.drop_index(op.f('ix_jus01_systemidentity_email'), table_name='jus01_systemidentity')
    op.drop_index('idx_identity_type', table_name='jus01_systemidentity')
    op.drop_index('idx_identity_status', table_name='jus01_systemidentity')
    op.drop_index('idx_identity_email', table_name='jus01_systemidentity')
    op.drop_index('idx_identity_active', table_name='jus01_systemidentity')
    op.create_unique_constraint('jus01_systemidentity_email_key', 'jus01_systemidentity', ['email'])
    op.create_index('ix_identity_type', 'jus01_systemidentity', ['identity_type'], unique=False)
    op.create_index('ix_identity_status', 'jus01_systemidentity', ['status'], unique=False)
    op.create_index('ix_identity_email', 'jus01_systemidentity', ['email'], unique=False)
    op.alter_column('jus01_systemidentity', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table_comment(
        'job_posting',
        'Labour market job postings for skills demand analysis',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_job_posting_posted_date'), table_name='job_posting')
    op.create_index('ix_job_region_month', 'job_posting', ['region', 'posting_month'], unique=False)
    op.create_index('ix_job_processed', 'job_posting', ['is_processed'], unique=False)
    op.create_index('ix_job_posting_year', 'job_posting', ['posting_year'], unique=False)
    op.create_index('ix_job_posting_month', 'job_posting', ['posting_month'], unique=False)
    op.create_index('ix_job_created_at', 'job_posting', ['created_at'], unique=False)
    op.drop_constraint(op.f('fk_dsl01_auditevent_token_id_sec01_authtoken'), 'dsl01_auditevent', type_='foreignkey')
    op.drop_index(op.f('ix_dsl01_auditevent_token_id'), table_name='dsl01_auditevent')
    op.drop_index(op.f('ix_dsl01_auditevent_actor_id'), table_name='dsl01_auditevent')
    op.drop_index('idx_audit_type_time', table_name='dsl01_auditevent')
    op.drop_index('idx_audit_token_time', table_name='dsl01_auditevent')
    op.drop_index('idx_audit_severity', table_name='dsl01_auditevent')
    op.create_index('ix_audit_type', 'dsl01_auditevent', ['event_type'], unique=False)
    op.create_index('ix_audit_token', 'dsl01_auditevent', ['token_id'], unique=False)
    op.create_index('ix_audit_result', 'dsl01_auditevent', ['result'], unique=False)
    op.create_index('ix_audit_event_time', 'dsl01_auditevent', ['event_time'], unique=False)
    op.create_index('ix_audit_actor_time', 'dsl01_auditevent', ['actor_id', 'event_time'], unique=False)
    op.create_index('ix_audit_actor', 'dsl01_auditevent', ['actor_id'], unique=False)
    op.alter_column('dsl01_auditevent', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_table_comment(
        'curriculum_module',
        'Curriculum modules for predictive alignment analysis',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_curriculum_module_programme'), table_name='curriculum_module')
    op.drop_index(op.f('ix_curriculum_module_nqf_level'), table_name='curriculum_module')
    op.drop_index(op.f('ix_curriculum_module_module_code'), table_name='curriculum_module')
    op.drop_index(op.f('ix_curriculum_module_faculty'), table_name='curriculum_module')
    op.create_index('ix_curriculum_nqf_level', 'curriculum_module', ['nqf_level'], unique=False)
    op.create_index('ix_curriculum_module_code', 'curriculum_module', ['module_code'], unique=False)
    op.create_index('ix_curriculum_faculty_nqf', 'curriculum_module', ['faculty', 'nqf_level'], unique=False)
    op.create_index('ix_curriculum_faculty', 'curriculum_module', ['faculty'], unique=False)
    op.create_index('ix_curriculum_active_code', 'curriculum_module', ['is_active', 'module_code'], unique=False)
    # ### end Alembic commands ###
