"""Add email to user

Revision ID: f8babc1394c7
Revises: 99cd0160796c
Create Date: 2026-03-07 09:18:59.888454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8babc1394c7'
down_revision: Union[str, Sequence[str], None] = '99cd0160796c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jus01_systemidentity', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'jus01_systemidentity', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jus01_systemidentity', type_='unique')
    op.drop_column('jus01_systemidentity', 'email')
    # ### end Alembic commands ###
